from automata.fa.Moore import Moore
import sys, os

from myerror import MyError

error_handler = MyError('LexerErrors')

global check_cm
global check_key

moore = Moore(
    states=['q_inicial', 'q_i', 'q_nINT', 'q_tINT', 'q_INT', 'q_ID', 'q_IF', 'q_ELSE', 'q_FLOAT', 'q_RETURN', 'q_vVOID', 'q_WHILE', 
                'q_PLUS', 'q_MINUS', 'q_TIMES', 'q_DIVIDE', 'q_LESS', 'q_LESS_EQUAL', 'q_GREATER', 'q_GREATER_EQUAL', 
                'q_EQUALS', 'q_DIFFERENT', 'q_ATTRIBUTION', 'q_NUMBER', 'q_LPAREN', 'q_RPAREN', 'q_LBRACKETS', 
                'q_RBRACKETS', 'q_LBRACES', 'q_RBRACES', 'q_SEMICOLON', 'q_COMMA',
                'q_IDDUPLICATE, q_NUMBERDUPLICADE', 'q_comment', 'q_commentFINAL', 'q_IDSEMICOLON'],
    input_alphabet=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',  
                    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '_', '+', '-', '*', '/', '<', '>', '=', '!', '(', ')', '[', ']', '{', '}', ';', ',', 
                    '.', ' ','\n'],
    output_alphabet=['IF', 'ELSE', 'INT', 'FLOAT', 'RETURN', 'VOID', 'WHILE',
                    'PLUS', 'MINUS', 'TIMES', 'DIVIDE', 
                    'LESS', 'LESS_EQUAL', 'GREATER', 'GREATER_EQUAL', 'EQUALS', 'DIFFERENT', 
                    'LPAREN', 'RPAREN', 'LBRACKETS', 'RBRACKETS', 'LBRACES', 'RBRACES', 'ATTRIBUTION', 
                    'SEMICOLON', 'COMMA', 'ID', 'NUMBER'],
    transitions={
                'q_inicial' : {
                    'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',       
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                },
                'q_comment':{                   
                    'a': 'q_comment', 'b': 'q_comment', 'c': 'q_comment', 'd': 'q_comment', 'e': 'q_comment', 'f': 'q_comment', 
                    'g': 'q_comment', 'h': 'q_comment', 'i': 'q_comment', 'j': 'q_comment', 'k': 'q_comment', 
                    'l': 'q_comment', 'm': 'q_comment', 'n': 'q_comment', 'o': 'q_comment', 'p': 'q_comment', 
                    'q': 'q_comment', 'r': 'q_comment', 's': 'q_comment', 't': 'q_comment', 'u': 'q_comment', 
                    'v': 'q_comment', 'w': 'q_comment', 'x': 'q_comment', 'y': 'q_comment', 'z': 'q_comment', 
                    '0': 'q_comment', '1': 'q_comment', '2': 'q_comment', '3': 'q_comment', '4': 'q_comment', 
                    '5': 'q_comment', '6': 'q_comment', '7': 'q_comment', '8': 'q_comment', '9': 'q_comment', 
                    '+': 'q_comment', '-': 'q_comment', '*': 'q_commentFINAL', '/': 'q_comment', '<': 'q_comment', 
                    '>': 'q_comment', '=': 'q_comment', '!': 'q_comment', 
                    '(': 'q_comment', ')': 'q_comment', '[': 'q_comment', ']': 'q_comment', '{': 'q_comment', 
                    '}': 'q_comment', ';': 'q_comment', ',': 'q_comment', 
                    '.': 'q_comment', ' ': 'q_comment', '\n': 'q_comment',
                },
                'q_commentFINAL':{
                    '/':'q_inicial',
                    'a': 'q_comment', 'b': 'q_comment', 'c': 'q_comment', 'd': 'q_comment', 'e': 'q_comment', 'f': 'q_comment', 
                    'g': 'q_comment', 'h': 'q_comment', 'i': 'q_comment', 'j': 'q_comment', 'k': 'q_comment', 
                    'l': 'q_comment', 'm': 'q_comment', 'n': 'q_comment', 'o': 'q_comment', 'p': 'q_comment', 
                    'q': 'q_comment', 'r': 'q_comment', 's': 'q_comment', 't': 'q_comment', 'u': 'q_comment', 
                    'v': 'q_comment', 'w': 'q_comment', 'x': 'q_comment', 'y': 'q_comment', 'z': 'q_comment', 
                    '0': 'q_comment', '1': 'q_comment', '2': 'q_comment', '3': 'q_comment', '4': 'q_comment', 
                    '5': 'q_comment', '6': 'q_comment', '7': 'q_comment', '8': 'q_comment', '9': 'q_comment', 
                    '+': 'q_comment', '-': 'q_comment', '*': 'q_comment', '<': 'q_comment', '>': 'q_comment', 
                    '=': 'q_comment', '!': 'q_comment', '(': 'q_comment', ')': 'q_comment', '[': 'q_comment', 
                    ']': 'q_comment', '{': 'q_comment', '}': 'q_comment', ';': 'q_comment', ',': 'q_comment', 
                    '.': 'q_comment', ' ': 'q_comment', '\n': 'q_comment',
                },
                'q_IDSEMICOLON':{
                    'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',       
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                },
                'q_i' : {
                    'n' : 'q_nINT',
                    'f' : 'q_IF',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_IDSEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_nINT' : {
                    't' : 'q_INT',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_IDSEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_tINT' : {
                    ' ' : 'q_INT',
                    '\n' : 'q_INT',
                 'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                                'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                                'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                                'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                                'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                                'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                
                },
                'q_INT':{
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                },
                'q_fIF': {
                    '\n': 'q_inicial',
                    ' ': 'q_inicial',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    
                    
                },
                'q_eELSE': {
                    'l':'q_lELSE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_lELSE':{
                    's':'q_sELSE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_sELSE':{
                    'e':'q_e2ELSE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_e2ELSE':{
                    '\n':'q_ELSE',
                    ' ': 'q_ELSE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    
                },
                'q_fFLOAT':{
                    'l':'q_lFLOAT',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_lFLOAT':{
                    'o':'q_oFLOAT',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_oFLOAT':{
                    'a':'q_aFLOAT',
                    'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_aFLOAT':{
                    't':'q_tFLOAT',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_tFLOAT':{
                    ' ':'q_FLOAT',
                    '\n': 'q_FLOAT',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    
                },
                'q_rRETURN':{
                    'e':'q_eRETURN',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_eRETURN':{
                    't':'q_tRETURN',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_tRETURN':{
                    'u':'q_uRETURN',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_uRETURN':{
                    'r':'q_r2RETURN',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_r2RETURN':{
                    'n':'q_RETURN',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_vVOID': {
                    'o':'q_oVOID',
                    ';':'q_IDSEMICOLON',
                    ',':'q_IDCOMMA',
                    '(': 'q_LPARENID', ')': 'q_RPARENID',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '[': 'q_LBRACKETS', ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_ID', '\n': 'q_ID'
                    
                },
                'q_oVOID': {
                    'i':'q_iVOID',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_ID', '\n': 'q_inicial'
                    
                },
                'q_iVOID': {
                    'd':'q_VOID',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_wWHILE':{
                    'h':'q_hWHILE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID',
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_hWHILE':{
                    'i':'q_iWHILE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_iWHILE':{
                    'l':'q_lWHILE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_lWHILE':{
                    'e':'q_eWHILE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
                    
                },
                'q_eWHILE':{
                    ' ':'q_WHILE',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                    'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                    'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS', '>': 'q_gGREATER', '=': 'q_eEQUAL', '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    
                },
                'q_NUMBER': {'0': 'q_NUMBERDUPLICADE', '1': 'q_NUMBERDUPLICADE', '2': 'q_NUMBERDUPLICADE', '3': 'q_NUMBERDUPLICADE', '4': 'q_NUMBERDUPLICADE',
                            '5': 'q_NUMBERDUPLICADE', '6': 'q_NUMBERDUPLICADE', '7': 'q_NUMBERDUPLICADE', '8': 'q_NUMBERDUPLICADE', '9': 'q_NUMBERDUPLICADE', 
                            '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                            '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                            ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                            '<': 'q_lLESS', '>': 'q_gGREATER', '=': 'q_eEQUAL', '!': 'q_dDIFFERENT', ' ': 'q_inicial', '\n':'q_inicial'
                },
                'q_NUMBERDUPLICADE': {
                        '0': 'q_NUMBERDUPLICADE', '1': 'q_NUMBERDUPLICADE', '2': 'q_NUMBERDUPLICADE', '3': 'q_NUMBERDUPLICADE', '4': 'q_NUMBERDUPLICADE',
                        '5': 'q_NUMBERDUPLICADE', '6': 'q_NUMBERDUPLICADE', '7': 'q_NUMBERDUPLICADE', '8': 'q_NUMBERDUPLICADE', '9': 'q_NUMBERDUPLICADE', 
                        '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                        '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                        ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                        '<': 'q_lLESS', '>': 'q_gGREATER', '=': 'q_eEQUAL', '!': 'q_dDIFFERENT', ' ': 'q_inicial', '\n':'q_inicial'    
                            },
                
                'q_ID': {'a': 'q_IDDUPLICATE', 'b': 'q_IDDUPLICATE', 'c': 'q_IDDUPLICATE', 'd': 'q_IDDUPLICATE', 
                        'e': 'q_IDDUPLICATE', 'f': 'q_IDDUPLICATE', 'g': 'q_IDDUPLICATE', 'h': 'q_IDDUPLICATE', 
                        'i': 'q_IDDUPLICATE', 'j': 'q_IDDUPLICATE', 'k': 'q_IDDUPLICATE', 'l': 'q_IDDUPLICATE',
                        'm': 'q_IDDUPLICATE', 'n': 'q_IDDUPLICATE', 'o': 'q_IDDUPLICATE', 'p': 'q_IDDUPLICATE',
                        'q': 'q_IDDUPLICATE', 'r': 'q_IDDUPLICATE', 's': 'q_IDDUPLICATE', 't': 'q_IDDUPLICATE',
                        'u': 'q_IDDUPLICATE', 'v': 'q_IDDUPLICATE', 'w': 'q_IDDUPLICATE', 'x': 'q_IDDUPLICATE',
                        'y': 'q_IDDUPLICATE', 'z': 'q_IDDUPLICATE',
                        '0': 'q_NUMBERDUPLICADE', '1': 'q_NUMBERDUPLICADE', '2': 'q_NUMBERDUPLICADE', '3': 'q_NUMBERDUPLICADE', '4': 'q_NUMBERDUPLICADE',
                        '5': 'q_NUMBERDUPLICADE', '6': 'q_NUMBERDUPLICADE', '7': 'q_NUMBERDUPLICADE', '8': 'q_NUMBERDUPLICADE', '9': 'q_NUMBERDUPLICADE',
                        '(': 'q_LPAREN', ';': 'q_SEMICOLON',')': 'q_RPAREN',',': 'q_COMMA', ' ': 'q_inicial',
                        '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                        '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                        ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                        '<': 'q_lLESS',
                        '>': 'q_gGREATER',
                        '=': 'q_eEQUAL',
                        '!': 'q_dDIFFERENT',
                },
                'q_IDDUPLICATE': {'a': 'q_IDDUPLICATE', 'b': 'q_IDDUPLICATE', 'c': 'q_IDDUPLICATE', 'd': 'q_IDDUPLICATE', 
                                'e': 'q_IDDUPLICATE', 'f': 'q_IDDUPLICATE', 'g': 'q_IDDUPLICATE', 'h': 'q_IDDUPLICATE', 
                                'i': 'q_IDDUPLICATE', 'j': 'q_IDDUPLICATE', 'k': 'q_IDDUPLICATE', 'l': 'q_IDDUPLICATE',
                                'm': 'q_IDDUPLICATE', 'n': 'q_IDDUPLICATE', 'o': 'q_IDDUPLICATE', 'p': 'q_IDDUPLICATE',
                                'q': 'q_IDDUPLICATE', 'r': 'q_IDDUPLICATE', 's': 'q_IDDUPLICATE', 't': 'q_IDDUPLICATE',
                                'u': 'q_IDDUPLICATE', 'v': 'q_IDDUPLICATE', 'w': 'q_IDDUPLICATE', 'x': 'q_IDDUPLICATE',
                                'y': 'q_IDDUPLICATE', 'z': 'q_IDDUPLICATE', '(': 'q_LPAREN', ';': 'q_SEMICOLON',')': 'q_RPAREN',',': 'q_COMMA', ' ': 'q_inicial'},
                'q_lLESS' :{
                    ' ': 'q_LESS',
                    '=': 'q_LESS_EQUAL',
                    'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                        'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                        'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                        'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                        'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                        'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID', 
                        'y':'q_ID', 'z' : 'q_ID', '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                        '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    
                },
                  'q_gGREATER' : {
                      ' ': 'q_GREATER',
                      '=' : 'q_GREATER_EQUAL',
                      'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                        'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                        'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                        'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                        'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                        'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID', 
                        'y':'q_ID', 'z' : 'q_ID', '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                        '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                },
                    'q_eEQUAL' : {
                        '=':'q_EQUALS',
                        ' ':'q_ATTRIBUTION',
                        'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                        'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                        'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                        'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                        'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                        'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID', 
                        'y':'q_ID', 'z' : 'q_ID', '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                        '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                       
                    
                },
                    'q_dDIFFERENT': {
                        '=': 'q_DIFFERENT',
                        'a': 'q_ID', 'b': 'q_ID', 'c': 'q_ID', 'd': 'q_ID', 
                        'e': 'q_ID', 'f': 'q_ID', 'g': 'q_ID', 'h': 'q_ID', 
                        'i': 'q_ID', 'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                        'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                        'q': 'q_ID', 'r': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                        'u': 'q_ID', 'v': 'q_ID', 'w': 'q_ID', 'x': 'q_ID', 
                        'y':'q_ID', 'z' : 'q_ID', '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                        '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                       
                },
            'q_IF': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_ELSE': {
               'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_FLOAT': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_RETURN': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_VOID': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_WHILE': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_PLUS': {
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_ID',
                'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_ID', '\n': 'q_inicial'
            },
            'q_MINUS': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_TIMES': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            }, 
            'q_DIVIDE': {
                'i' : 'q_DIVIDEID',
                'e' : 'q_DIVIDEID',
                'f' : 'q_DIVIDEID',
                'r' : 'q_DIVIDEID',
                'v' : 'q_DIVIDEID',
                'w' : 'q_DIVIDEID',
                'a': 'q_DIVIDEID',
                'b': 'q_DIVIDEID',
                'c': 'q_DIVIDEID',
                'd': 'q_DIVIDEID',
                'g': 'q_DIVIDEID', 'h': 'q_DIVIDEID', 
                'j': 'q_DIVIDEID', 'k': 'q_DIVIDEID', 'l': 'q_DIVIDEID',
                'm': 'q_DIVIDEID', 'n': 'q_DIVIDEID', 'o': 'q_DIVIDEID', 'p': 'q_DIVIDEID',
                'q': 'q_DIVIDEID', 's': 'q_DIVIDEID', 't': 'q_DIVIDEID',
                'u': 'q_DIVIDEID', 'x': 'q_DIVIDEID',
                'y': 'q_DIVIDEID', 'z': 'q_DIVIDEID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_comment',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_DIVIDENUMBER', '1': 'q_DIVIDENUMBER', '2': 'q_DIVIDENUMBER', '3': 'q_DIVIDENUMBER', '4': 'q_DIVIDENUMBER',
                '5': 'q_DIVIDENUMBER', '6': 'q_DIVIDENUMBER', '7': 'q_DIVIDENUMBER', '8': 'q_DIVIDENUMBER', '9': 'q_DIVIDENUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_DIVIDEID':{
                ' ': 'q_inicial', '\n': 'q_inicial',
                'a': 'q_IDDUPLICATE', 'b': 'q_IDDUPLICATE', 'c': 'q_IDDUPLICATE', 'd': 'q_IDDUPLICATE', 
                'e': 'q_IDDUPLICATE', 'f': 'q_IDDUPLICATE', 'g': 'q_IDDUPLICATE', 'h': 'q_IDDUPLICATE', 
                'i': 'q_IDDUPLICATE', 'j': 'q_IDDUPLICATE', 'k': 'q_IDDUPLICATE', 'l': 'q_IDDUPLICATE',
                'm': 'q_IDDUPLICATE', 'n': 'q_IDDUPLICATE', 'o': 'q_IDDUPLICATE', 'p': 'q_IDDUPLICATE',
                'q': 'q_IDDUPLICATE', 'r': 'q_IDDUPLICATE', 's': 'q_IDDUPLICATE', 't': 'q_IDDUPLICATE',
                'u': 'q_IDDUPLICATE', 'v': 'q_IDDUPLICATE', 'w': 'q_IDDUPLICATE', 'x': 'q_IDDUPLICATE',
                'y': 'q_IDDUPLICATE', 'z': 'q_IDDUPLICATE',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
            },
            'q_DIVIDENUMBER':{
                ' ': 'q_inicial', '\n': 'q_inicial',
                'a': 'q_IDDUPLICATE', 'b': 'q_IDDUPLICATE', 'c': 'q_IDDUPLICATE', 'd': 'q_IDDUPLICATE', 
                'e': 'q_IDDUPLICATE', 'f': 'q_IDDUPLICATE', 'g': 'q_IDDUPLICATE', 'h': 'q_IDDUPLICATE', 
                'i': 'q_IDDUPLICATE', 'j': 'q_IDDUPLICATE', 'k': 'q_IDDUPLICATE', 'l': 'q_IDDUPLICATE',
                'm': 'q_IDDUPLICATE', 'n': 'q_IDDUPLICATE', 'o': 'q_IDDUPLICATE', 'p': 'q_IDDUPLICATE',
                'q': 'q_IDDUPLICATE', 'r': 'q_IDDUPLICATE', 's': 'q_IDDUPLICATE', 't': 'q_IDDUPLICATE',
                'u': 'q_IDDUPLICATE', 'v': 'q_IDDUPLICATE', 'w': 'q_IDDUPLICATE', 'x': 'q_IDDUPLICATE',
                'y': 'q_IDDUPLICATE', 'z': 'q_IDDUPLICATE',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
            },
            'q_LESS': {
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_LESS_EQUAL': {
               'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_GREATER': {
               'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            }, 
            'q_GREATER_EQUAL': {
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_EQUALS': {
               'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_DIFFERENT': {
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_LPAREN': {
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_RPAREN': {
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_LPARENID' :{
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_RPARENID':{
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_LBRACKETS': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_RBRACKETS': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_LBRACES': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_RBRACES': {
               'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_SEMICOLON': {
                'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            }, 
            'q_COMMA': {
                'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_IDCOMMA':{
                 'i' : 'q_i',
                'e' : 'q_eELSE',
                'f' : 'q_fFLOAT',
                'r' : 'q_rRETURN',
                'v' : 'q_vVOID',
                'w' : 'q_wWHILE',
                'a': 'q_ID',
                'b': 'q_ID',
                'c': 'q_ID',
                'd': 'q_ID',
                'g': 'q_ID', 'h': 'q_ID', 
                'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                'u': 'q_ID', 'x': 'q_ID',
                'y': 'q_ID', 'z': 'q_ID',
                '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                '<': 'q_lLESS',
                '>': 'q_gGREATER',
                '=': 'q_eEQUAL',
                '!': 'q_dDIFFERENT',
                '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                ' ': 'q_inicial', '\n': 'q_inicial'
            },
            'q_ATTRIBUTION': {
               'i' : 'q_i',
                    'e' : 'q_eELSE',
                    'f' : 'q_fFLOAT',
                    'r' : 'q_rRETURN',
                    'v' : 'q_vVOID',
                    'w' : 'q_wWHILE',
                    'a': 'q_ID',
                    'b': 'q_ID',
                    'c': 'q_ID',
                    'd': 'q_ID',
                    'g': 'q_ID', 'h': 'q_ID', 
                    'j': 'q_ID', 'k': 'q_ID', 'l': 'q_ID',
                    'm': 'q_ID', 'n': 'q_ID', 'o': 'q_ID', 'p': 'q_ID',
                    'q': 'q_ID', 's': 'q_ID', 't': 'q_ID',
                    'u': 'q_ID', 'x': 'q_ID',
                    'y': 'q_ID', 'z': 'q_ID',
                    '+': 'q_PLUS', '-': 'q_MINUS', '*': 'q_TIMES', '/': 'q_DIVIDE',
                    '(': 'q_LPAREN', ')': 'q_RPAREN', '[': 'q_LBRACKETS',
                    ']': 'q_RBRACKETS', '{': 'q_LBRACES', '}': 'q_RBRACES', ';': 'q_SEMICOLON', ',': 'q_COMMA',
                    '<': 'q_lLESS',
                    '>': 'q_gGREATER',
                    '=': 'q_eEQUAL',
                    '!': 'q_dDIFFERENT',
                    '0': 'q_NUMBER', '1': 'q_NUMBER', '2': 'q_NUMBER', '3': 'q_NUMBER', '4': 'q_NUMBER',
                    '5': 'q_NUMBER', '6': 'q_NUMBER', '7': 'q_NUMBER', '8': 'q_NUMBER', '9': 'q_NUMBER',
                    ' ': 'q_inicial', '\n': 'q_inicial'
            },
},
    initial_state='q_inicial',
    output_table= {
            'q_IF': 'IF',
            'q_ELSE': 'ELSE',
            'q_INT': 'INT',
            'q_FLOAT': 'FLOAT',
            'q_RETURN': 'RETURN',
            'q_VOID': 'VOID',
            'q_WHILE': 'WHILE',
            'q_PLUS': 'PLUS',
            'q_MINUS': 'MINUS',
            'q_TIMES': 'TIMES', 
            'q_DIVIDEID' : 'DIVIDE\nID',
            'q_DIVIDENUMBER':'DIVIDE\nNUMBER',
            'q_LESS': 'LESS',
            'q_LESS_EQUAL': 'LESS_EQUAL',
            'q_GREATER': 'GREATER', 
            'q_GREATER_EQUAL': 'GREATER_EQUAL',
            'q_EQUALS': 'EQUALS',
            'q_DIFFERENT': 'DIFFERENT',
            'q_LPAREN': 'LPAREN',
            'q_RPAREN': 'RPAREN',
            'q_LBRACKETS': 'LBRACKETS',
            'q_RBRACKETS': 'RBRACKETS',
            'q_LBRACES': 'LBRACES',
            'q_RBRACES': 'RBRACES',
            'q_SEMICOLON': 'SEMICOLON', 
            'q_COMMA': 'COMMA',
            'q_ATTRIBUTION': 'ATTRIBUTION',
            'q_ID' : 'ID',
            'q_NUMBER':'NUMBER',
            'q_IDSEMICOLON':'ID\nSEMICOLON',
            'q_IDCOMMA':'ID\nCOMMA',
            'q_LPARENID' :'ID\nLPAREN',
            'q_RPARENID' : 'ID\nRPAREN',
        }
)

def main():
    check_cm = False
    check_key = False
    
    for idx, arg in enumerate(sys.argv):
        # print("Argument #{} is {}".format(idx, arg))
        aux = arg.split('.')
        if aux[-1] == 'cm':
            check_cm = True
            idx_cm = idx

        if(arg == "-k"):
            check_key = True
    
    # print ("No. of arguments passed is ", len(sys.argv))

    if(len(sys.argv) < 3):
        raise TypeError(error_handler.newError(check_key, 'ERR-LEX-USE'))

    if not check_cm:
      raise IOError(error_handler.newError(check_key, 'ERR-LEX-NOT-CM'))
    elif not os.path.exists(sys.argv[idx_cm]):
        raise IOError(error_handler.newError(check_key, 'ERR-LEX-FILE-NOT-EXISTS'))
    else:
        data = open(sys.argv[idx_cm])
        source_file = data.read()

        if not check_key:
            print("Definição da Máquina")
            print(moore)
            print("Entrada:")
            print(source_file)
            print("Lista de Tokens:")
        
        estado = moore.initial_state  # Inicializa o estado APENAS uma vez
        tokens = []
        for caracter in source_file:
            # print(f"Estado: {estado}")
            # print(f"Caracter: {caracter}")
            novo_estado = moore.transitions.get(estado, {}).get(caracter)
            # print(f"Novo estado: {novo_estado}\n")
            if novo_estado in moore.output_table:
                tokens.append(moore.output_table[novo_estado])
                # print(f"token: {moore.output_table[novo_estado]}\n")
            estado = novo_estado
        
        
        for token in tokens:
            print(token)
        # print(moore.get_output_from_string(source_file))

if __name__ == "__main__":

    try:
        main()
    except Exception as e:
        print(e)
    except (ValueError, TypeError):
        print(e)